kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
networking:
  podSubnet: 10.1.0.0/16
controlPlaneEndpoint: ha-control-plane
kubernetesVersion: v1.27.0
---
kind: JoinConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    apiServerEndpoint: ha-control-plane:6443
    token: <token>
    unsafeSkipCAVerification: true 
    caCertHashes:
      - <ca-cert-hash>
nodeRegistration:
  criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  name: <node-name>
  taints: null
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd